# Generated by Django 5.0.4 on 2024-04-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被软删除', verbose_name='是否被软删除')),
                ('created_by', models.CharField(default='admin', max_length=64, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(default='admin', max_length=64, null=True, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('identifier', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='角色唯一标识符')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='角色名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, help_text='True 标识启用 False表示禁用', verbose_name='启用/禁用')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'backend_role',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuButtonPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_range', models.IntegerField(choices=[(0, '仅本人数据权限'), (1, '本部门及以下数据权限'), (2, '本部门数据权限'), (3, '全部数据权限')], default=0, help_text='数据权限范围', verbose_name='数据权限范围')),
                ('menu_button', models.ForeignKey(db_constraint=False, help_text='关联菜单按钮', on_delete=django.db.models.deletion.CASCADE, related_name='menu_button_permission', to='permission.menubutton', verbose_name='关联菜单按钮')),
                ('role', models.ForeignKey(db_constraint=False, help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_button', to='role.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '角色接口权限表',
                'verbose_name_plural': '角色接口权限表',
                'db_table': 'backend_role_menuButton',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='permission.menu', verbose_name='关联菜单')),
                ('role', models.ForeignKey(db_constraint=False, help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='role.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '角色菜单权限表',
                'verbose_name_plural': '角色菜单权限表',
                'db_table': 'backend_role_menu',
            },
        ),
    ]
