# Generated by Django 5.0.4 on 2024-04-15 04:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否被软删除', verbose_name='是否被软删除')),
                ('created_by', models.CharField(default='admin', max_length=64, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(default='admin', max_length=64, null=True, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(db_index=True, error_messages={'unique': '该用户已存在'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('display_name', models.CharField(max_length=150, null=True, verbose_name='显示名')),
                ('password', models.CharField(max_length=126, null=True, verbose_name='密码')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, help_text='性别', null=True, verbose_name='性别')),
                ('source', models.IntegerField(choices=[(0, '本地用户'), (1, 'AD域账号')], default=0, verbose_name='用户来源')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, help_text='True 标识启用 False表示禁用', verbose_name='启用/禁用')),
                ('last_deactivate', models.DateTimeField(null=True, verbose_name='最近用户被禁用时间')),
                ('last_login', models.DateTimeField(null=True, verbose_name='最后登录时间')),
                ('last_change_password', models.DateTimeField(null=True, verbose_name='最后修改密码时间')),
                ('groups', models.ManyToManyField(blank=True, db_constraint=False, related_name='group_users', to='group.group', verbose_name='用户组')),
                ('roles', models.ManyToManyField(blank=True, db_constraint=False, related_name='role_users', to='role.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'backend_user',
                'unique_together': {('username',)},
            },
        ),
    ]
