# Generated by Django 5.0.4 on 2024-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True 标识启用 False表示禁用', verbose_name='启用/禁用'),
        ),
    ]
