# Generated by Django 5.0.4 on 2024-04-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubutton',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='permission.menu', verbose_name='关联菜单'),
        ),
    ]
